server:
  port: 9090
spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.26:8837,192.168.3.26:8848,192.168.3.26:8859
      config:
        server-addr: 192.168.3.26:8837,192.168.3.26:8848,192.168.3.26:8859
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true #   gateway可以从nacos中发现服务
      routes:
        - id: user-service # 这个是路由id，随便起个名，只要唯一就行
          uri: lb://user-service #这个是强制对映的，对应子模块的名字，即：spring.application.name=user-service 配置文件里的配置
          predicates: #断言
            - Path=/**
          filters:
            - StripPrefix=1
        - id: oauth2-service
          uri: lb://oauth2-service
          predicates: #断言
            - Path=/**
          filters:
            - StripPrefix=1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.26:3306/oauth?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root



